const axios = require("axios");
const storage = require("./storage");

function spotifyApi(token) {
  return axios.create({
    baseURL: "https://api.spotify.com/v1",
    headers: { Authorization: `Bearer ${token}` },
  });
}

async function getOrCreate(userId, token, name) {
  const existing = await storage.getPlaylist(userId, name);
  if (existing) return existing;

  const api = spotifyApi(token);
  try {
    const res = await api.post(`/me/playlists`, {
      name,
      public: false,
      description: "Auto-generated by Collectify 🎵",
    });
    const playlistId = res.data.id;
    await storage.savePlaylist(userId, name, playlistId);
    return playlistId;
  } catch (err) {
    console.error("Playlist creation error:", err.response?.data);
    throw err;
  }
}

async function addTrack(token, playlistId, trackUri) {
  const api = spotifyApi(token);
  await api.post(`/playlists/${playlistId}/items`, {
    uris: [trackUri],
  });
}

async function getPlaylistId(userId, token, mode, track) {
  const today = new Date().toISOString().split("T")[0];

  if (mode === "alltime") {
    return getOrCreate(userId, token, "Full Listens ✓");
  }
  if (mode === "daily") {
    return getOrCreate(userId, token, `Full Listens : ${today}`);
  }
  if (mode === "session") {
    const user = await storage.getUser(userId);
    if (user.session_playlist_id) return user.session_playlist_id;
    const label = new Date().toLocaleString("en-GB", {
      dateStyle: "short",
      timeStyle: "short",
    });
    const id = await getOrCreate(userId, token, `Session ${label}`);
    await storage.updateSessionPlaylist(userId, id);
    return id;
  }
  if (mode === "genre") {
    const api = spotifyApi(token);
    const artistId = track.artists[0].id;
    const artistRes = await api.get(`/artists/${artistId}`);
    const genres = artistRes.data.genres;
    const genre = genres[0] || "Unknown Genre";
    const label = genre.charAt(0).toUpperCase() + genre.slice(1);
    return getOrCreate(userId, token, `Full Listens : ${label}`);
  }

  throw new Error(`Unknown mode: ${mode}`);
}

module.exports = { addTrack, getPlaylistId };
